FROM memsql/cluster-in-a-box:latest

ENV LICENSE_KEY=BGI3ZjYwNWNlYmJiYTRiYmQ5YmUzNmY0Mjk1N2JjY2IzAAAAAAAAAAAEAAAAAAAAAAwwNQIYDu8jVYOBgjKCn8IW+p9fI+ZyBnnJYrvdAhkAt+zIJmRW3RWmCjZGELIeSJQiTiXjfDwLAA==

COPY tpch/* /tmp/
COPY init.sh /home/memsql/

#RUN chmod -R 777 /home/memsql


